### ISSUE TITLE
publish to npm ?

### ISSUE THREAD

**Issue by kapouer** [webcomponents/URL#21]
Please ?

**Comment by bonjowi** [comment]
https://www.npmjs.com/package/@publica/url-polyfill

**Comment by cmawhorter** [comment]
that npm module is marked deprecated and links to this repo.  is it this repo? 😕 

there was talk of [whatwg-url](https://github.com/jsdom/whatwg-url) elsewhere here, which exports both URL and URLSearchParams. after switching a project to it, afaict it seems to be drop-in-able (except it doesn't auto polyfill).

**Comment by TimvdLippe** [comment]
This package is published as https://www.npmjs.com/package/@webcomponents/url

**Comment by cmawhorter** [comment]
IIRC webcomponents/url had an issue/quirk/something, which is what led me to publica/url-polyfill in the first place.  I don't remember what that issue was (possibly rollup related) and have no idea if it has been resolved.

Is the world in agreement webcomponents/url is _the_ place to go for url polyfill?

the last non-metadata commit to this repo that actually changed code was [Dec 2016](https://github.com/webcomponents/URL/commit/4758781bba9226795d094528c2b66dce42538a85)...
